### ISSUE TITLE
Encrypt/Decrypt

### ISSUE THREAD

**Issue by kidkanjas** [DaggerES/ReloadCam#1]
NO ES UNA ENCRIPTACION MUY SEGURA! Es un simple Vigenere
Pon un breakpoint aqui si quieres ver la URL verdadera
DaggerES:
¿Puede dar un ejemplo de cómo hacerlo?

Lo de encriptarla no es dificil y se puede hacer con un print ReloadCam_Helper.Encript("URLSINENCRIPTAR")
DaggerES:
¿Puede dar un ejemplo de cómo hacerlo?

**Comment by gavazquez** [comment]
Por ejemplo. Para ver la url verdadera del server raul7:

1-Pon un breakpoint en la linea 18 del archivo ------> ReloadCam_Server_Raul7.py
2-Ejecuta el reloadCam con el parametro "-s Raul7"
3- Veras cual es la web real viendo el valor de la variable "realUrl"
4- Alternativamente sino, puedes escribir --> print realUrl en la linea 19 y te saldra ese valor

---

Supon que quieres encriptar "www.google.com"

Pues simplemente escribes print ReloadCam_Helper.Encript("www.google.com")
y te saldra impreso en pantalla la URL encriptada

**Comment by kidkanjas** [comment]
Una vez más mis agradecimientos  desde Portugal por su magnifico trabajo e volontad de compartirlo.
Estoy usando 'Visual Studio Code' en Windows10 con CTRL+SHIFT+B para ejecutar los phyton scripts..
Quando escribo print realUrl en la linea 19 e le doy el comando para ejecutar me sale siempre: SyntaxError: invalid syntax
Que estoy haciendo errado ?
Me gustaria poner um breakpoint em linea 18, pero:
Que diablo és um breakpoint ? Um numero, una expressión que és ?

**Comment by gavazquez** [comment]
Un breakpoint: 
https://pt.wikipedia.org/wiki/Ponto_de_parada

Mediante un breakpoint vas a poder ver el valor de cada variable en esa linea en concreto, luego puedes ir avanzando linea a linea y meterte dentro de funciones etc...

Verifica que version de python te has instalado. El script esta hecho para funcionar en python 2.7
Se que en python 3.X cambiaron el comando "print" y se escribe diferente print(realUrl)

Veo que estas empezando programacion asi que como IDE te recomiendo pycharm
https://www.jetbrains.com/pycharm/ 

Cuando la domines bien y sepas usarla entonces bajate el VisualStudio, pero empieza por lo facil ;)

**Comment by kidkanjas** [comment]
Gracias por tu rapida resposta.
No es que vaya a empezar programacion, no tiengo veleidad para eso, pero tengo ja he instalado el 'Pycharm'... quanto a dominar-lo... bién... no se me afigura tarea facil. Desde mi 'dreambox 800se' y desde 'Visual Studio Code' (después de configurarle el task runner para python le doy CTRL+SHIFT+B) soy capaz de ejecutar sin dificiuldad tus scripts. 
Tengo el python 2.7 en dreambox e en PC. Queria empezar por lo facil, pero con Pycharm ni da para empezar.
Mi foco eres tan solo aprender como encryptar/desencryptar las URL's de tu fantastico script, para quando cambién las pueda arreglar. La wiki de breakpoint no ayuda mucho,entiendo ser algo que se pone en modo de depuracion, que cambiará el script más que dejaria intactas sus funcionalidades.
1-Pon un breakpoint en la linea 18 del archivo ------> ReloadCam_Server_Raul7.py
Con 'Pycharm' es possible poner este breakpoint ? Puedes dar-me el camino completo para inserir esse breakpoint  en linea 18 del script ?
2-Escribes print ReloadCam_Helper.Encript("www.google.com")
y te saldra impreso en pantalla la URL encriptada
Tengo el folder ReloadCam_master con todos los py files abierto en Pycharm ? Y ahora donde escribo 'print ReloadCam_Helper.Encript("www.google.com")' ?

**Comment by gavazquez** [comment]
OK te doy un ejemplo:

En ReloadCam.py:

Linea 159 a 163:
`if __name__ == "__main__":`
`print "Getting latest file versions and checking for updates..."`
`DownloadScript("ReloadCam_Versions")`
`RefreshFiles()`
`Main()`

Cambias eso por esto:

`if __name__ == "__main__":`
`import ReloadCam_Helper`
`print ReloadCam_Helper.Encript("www.google.com")`         `ReloadCam_Helper.Decrypt("maanpLZ7fKHJ29LUkpihopuvpnvV1NmexdOUp6CZsbV81pSdssq9oYmpgIq6v-GS2MezrHJ0o3qGcrfZqaDHxqV0n4GcpLSDx7m_t5SlgmGYmKy1")`

`print "Getting latest file versions and checking for updates..."`
`DownloadScript("ReloadCam_Versions")`
`RefreshFiles()`
`Main()`

---

Con eso podras encriptar y desencriptar.
Ten cuidado y pon las tabulaciones correctamente!

Para poner breakpoints en visual studio charm aqui tienes un manual:

https://code.visualstudio.com/docs/editor/debugging#_breakpoints

Se ponen haciendo click en el margen de la ventana de codigo hasta que aparezca una "bolita" como esta:
https://i3-vso.sec.s-msft.com/get-started/code/_img/debug-app/DBG_VSCOM_SetBreakpoint.png

**Comment by kidkanjas** [comment]
gracias amigo por tu paciencia
el codigo certamente lo escribiste a la mano  donde tienes helper.encript sera bien helper.encrypt.
me salia un error en esa linea y era eso.El script funciona con esa modificacion pero en relacion a encritar/desencriptar las urls nada de nada.Suspecho que este cambio seja una condicion necesaria pero no suficiente, verdad ? Hay que poner tambien los breakpoints en los py de los servers, no ?

**Comment by gavazquez** [comment]
Si, lo ideal es que pongas breakpoints.

Ups si, es helper.encrypt
Con ese codigo en la ventana de python (la de color negro de ms-dos) te deberian salir las url encriptadas y desencriptadas, ya que estas llamando a esa funcion.

De todas formas, lo de los breakpoints es la mejor opcion, programar no es dificil y hay varios tutoriales en youtube, ademas python no es complicado ;)

**Comment by kidkanjas** [comment]
es un camino con demasiadas piedras para mi....

Con  reloadcam.py original:
Getting latest file versions and checking for updates...
Comparing local files with latest version...
Now getting Raul7 clines!
Writing to the cccam.cfg!
Restarting cam!
Finished!!!
Con reloadcam.py modificado
qKmqYqqwvNnR0Z3E054=
Getting latest file versions and checking for updates...
Comparing local files with latest version...
Now getting Raul7 clines!
Writing to the cccam.cfg!
Restarting cam!
Finished!!!
Lo que veo diferente es que me sale más: qKmqYqqwvNnR0Z3E054=
No es una URL tanpoco sera una cyfra vigenere.. voy a desistir e cerrar este issue.
De todos los modos gracias por tu tiempo e volontad de ayudar.

**Comment by gavazquez** [comment]
qKmqYqqwvNnR0Z3E054= <---------- es la web de google.com encriptada.

Se me olvido poner el "print" delante de ReloadCam_Helper.Decrypt("maanpLZ7fKHJ29LUkpihopuvpnvV1NmexdOUp6CZsbV81pSdssq9oYmpgIq6v-GS2MezrHJ0o3qGcrfZqaDHxqV0n4GcpLSDx7m_t5SlgmGYmKy1")

Asi que tu reloadcam.py deberia ser:

`if __name__ == "__main__":`
`import ReloadCam_Helper`
`print ReloadCam_Helper.Encript("www.google.com")`
 `print ReloadCam_Helper.Decrypt("maanpLZ7fKHJ29LUkpihopuvpnvV1NmexdOUp6CZsbV81pSdssq9oYmpgIq6v-GS2MezrHJ0o3qGcrfZqaDHxqV0n4GcpLSDx7m_t5SlgmGYmKy1")`

`print "Getting latest file versions and checking for updates..."`
`DownloadScript("ReloadCam_Versions")`
`RefreshFiles()`
`Main()`

**Comment by kidkanjas** [comment]
En este mundo de la programación  los pequeños detalles marcan la diferencia . Ahora funciona perfectamente. Tu trabajo era algo que faltaba en mundo de CS durante mucho tiempo . Ahora bien, si  puderas  adaptarlo de modo a que las clines se actualiazacen tambien en oscam.server eso si seria un completo festival....y pelo que veo ja estas mirando ese assunto.Hay que tener cuidado que en los foros satelite ni todo es lo que parece.Y los payservers ya deben estar haciendo tu cruz.

**Comment by kidkanjas** [comment]
Dagger,
Abajo esta el output quando busco elaissaoui con el reloadcam.py mod.

qKmqYqqwvNnR0Z3E054=
https://docs.google.com/document/d/1CiYpWvLGyro-lXRHABpFC1jgD4XeACmNhas6UTSH3AQ/edit
Getting latest file versions and checking for updates...
Comparing local files with latest version...
Now getting Elaissaoui clines!
ERROR!!!! NO CCCAMS LOADED!

Me sale ese error porque a URL de Elaissaoui esta mal.

Me sale la URL de google encrypted e la de raul7t decrypted.Claro que son los parametros que hay definido en el reloadcam.py y si los modifico obtengo claro otros resultados.
Pero interessante fuera que  salira automaticamente la web de elaissaoui (o otro que busque) encrypted & decrypted para que la pueda arreglar si necesario.
Los print encrypt/decrypt deberián establecer otra ruta
Sera que tienes alguna solucion para eso ?

**Comment by kidkanjas** [comment]
Dagger,
No hay necesidad de responder a la pregunta que le formulé en el issue anteriori porque mientras tanto ya he descubierto la solución.
Podría isso si  dar una mirada al  script cccam4you que tiene la URL correcta, pero no importa la cline.

**Comment by gavazquez** [comment]
Cierto, tengo que ver las url's porque varias han cambiado... a ver si este fin de semana saco algo de tiempo...
