### ISSUE TITLE
Recomendación para el proyecto

### ISSUE THREAD

**Issue by 3clypse** [DaggerES/ReloadCam#11]
Hola, ante todo enhorabuena y gracias por este tipo de proyectos.
He probado cómo funciona y testeas las líneas antes de añadirlas al fichero final que se introducirá en el deco. Esto sin embargo no es recomendable en todos los casos, ya que en ocasiones los servidores limitan el uso y conexión de la línea únicamente a la misma ip que hizo la petición.
Es decir, que si sacas la línea con tu ip y testious la testea con su ip (distintas) algunas de esas líneas tendrán un estado de OFF o FAKE en testious, cuando no es realmente así.
Espero que se haya entendido mi propuesta.

Un saludo.

**Comment by gavazquez** [comment]
El programa no usa testious, usa un metodo propio para testearla. 

https://github.com/DaggerES/CLineTester
