### ISSUE TITLE
Nuevos generadores

### ISSUE THREAD

**Issue by aiphonero** [DaggerES/ReloadCam#6]
Perdón si me repito tanto en las fuentes como en los posibles impedimentos para recoger las clines explicadas en otros issues.
- http://api.appsgateway.net/csp/Api/GeneratorFrame.aspx
- http://06.hack-sat.org/ddeerr444/  --> aqui me detecta adblock (espero que no sea impedimiento para el script)
- http://kyngcccam.com  --> pide user y pass para generar linea (user y pass para la linea, no tenemos que registrarnos en ningun lado)
- http://satunivers.ddns.net/cc/index.php#generator  --> no la entiendo muy bien y me indica (ahora) que el "server is full"
- http://b1.hack-sat.org/apoiooo/  --> aqui me detecta adblock (espero que no sea impedimiento para el script)
- http://star.hack-sat.org/875teioo/   --> aqui me detecta adblock (espero que no sea impedimiento para el script)

Intento pasarte más por algún privado. Si esto tiene manera de pasarte privados.

**Comment by gavazquez** [comment]
Muchas gracias por la aportacion!!

Voy a mirar a ver si puedo añadirlos y que tal van...

**Comment by gavazquez** [comment]
Hola, he podido añadir todas excepto la primera:

http://api.appsgateway.net/csp/Api/GeneratorFrame.aspx  ---> No se puede hacer ya que es por aspx :(
