### ISSUE TITLE
Enlaces

### ISSUE THREAD

**Issue by verbaton** [DaggerES/ReloadCam#9]
Te dejo aquí algunos enlaces que suelo poner yo a mano en el deco. Lo saque de algún foro que ya no encuentro XD Espero que alguno valga:

http://www.cccam.co/free-cccam-account/
http://free-cccam.com/freecccam/get.php
http://api.appsgateway.net/csp/Api/GeneratorFrame.aspx
http://b1.hack-sat.org
http://rcccam.esy.es/generator.htm 
http://www.cccamgate.com/cccam-test.php
http://www.cccamlux.com/Free-CCcam.php
http://amine1313dz.me.ma/12379.html
http://generator.cccamcafard.com/eurocccam/
http://hdpak.net/freetest/
http://cccamaster.com/cccam-test/
http://s1.satunivers.tv/gc/index.php#generator
http://infosat.satunivers.tv/cgn/indexfr.php
http://fullhd.hack-sat.org/
http://cccammania.com/free-cccam/
http://cccamfreeserver.com/cccam-free/
http://generator.cccamcafard.com/
http://onecccam.com/free_cccam_generator/
http://cccamspot.com/spot/get.php
https://cccam-tv.com/loading-gen1.html
http://urliptv.com/cccam/generator/48hours/index.php

Saludos

**Comment by gavazquez** [comment]
Gracias! intentare poner los que pueda ;)

**Comment by verbaton** [comment]
Gracias a ti, cualquier cosa. Aquí estamos. 
Saludos!
